directives:
  child-src: "'self'"
  connect-src: "'self' blob:"
  default-src: "'none'"
  font-src: "'self'"
  frame-ancestors: "'self'"
  frame-src: "'self' blob:"
  img-src: "'self' data: blob:"
  manifest-src: "'self'"
  media-src: "'self' blob:"
  object-src: "'self' blob:"
  script-src: "'self' 'unsafe-inline' 'unsafe-eval'"
  style-src: "'self' 'unsafe-inline'"
